# Generated by Django 4.2.5 on 2023-11-01 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditem',
            old_name='Category',
            new_name='category',
        ),
    ]
