# Generated by Django 4.2.5 on 2023-11-15 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_medicine_lobby_delete_fooditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine_lobby',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Medlist', to='menu.category'),
        ),
    ]
